/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package verkkopankki.gui;

import javax.swing.JFrame;
import verkkopankki.logiikka.Jarjestelma;

/**
 *
 * @author oskajoha
 */
public class EtusivuFeikki extends JFrame {

    private final Jarjestelma j;
    private final JFrame frame;
    /**
     * Creates new form Etusivu
     */
    
    public EtusivuFeikki(JFrame frame, Jarjestelma j) {
        this.frame = frame;
        this.j = j;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tilitLabel = new javax.swing.JLabel();
        kortitLabel = new javax.swing.JLabel();
        tiliPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        korttiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jToolBar1 = new javax.swing.JToolBar();
        kirjauduUlosNappi = new javax.swing.JButton();
        omatTiedotNappi = new javax.swing.JButton();
        uusiMaksuNappi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(180, 180, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(190, 200, 240));

        tilitLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tilitLabel.setText("Tilit");

        kortitLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kortitLabel.setText("Pankkikortit");

        tiliPanel.setLayout(new java.awt.GridLayout(8, 1));
        tiliPanel.add(jScrollPane3);

        javax.swing.GroupLayout korttiPanelLayout = new javax.swing.GroupLayout(korttiPanel);
        korttiPanel.setLayout(korttiPanelLayout);
        korttiPanelLayout.setHorizontalGroup(
            korttiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        korttiPanelLayout.setVerticalGroup(
            korttiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tilitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(tiliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kortitLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(korttiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(694, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tilitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kortitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(korttiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tiliPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        kirjauduUlosNappi.setText("Kirjaudu ulos");
        kirjauduUlosNappi.setFocusable(false);
        kirjauduUlosNappi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        kirjauduUlosNappi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(kirjauduUlosNappi);

        omatTiedotNappi.setText("Omat tiedot");
        omatTiedotNappi.setFocusable(false);
        omatTiedotNappi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        omatTiedotNappi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(omatTiedotNappi);

        uusiMaksuNappi.setText("Uusi maksu");
        uusiMaksuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uusiMaksuNappiActionPerformed(evt);
            }
        });
        jToolBar1.add(uusiMaksuNappi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uusiMaksuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uusiMaksuNappiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uusiMaksuNappiActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton kirjauduUlosNappi;
    private javax.swing.JLabel kortitLabel;
    private javax.swing.JPanel korttiPanel;
    private javax.swing.JButton omatTiedotNappi;
    private javax.swing.JPanel tiliPanel;
    private javax.swing.JLabel tilitLabel;
    private javax.swing.JButton uusiMaksuNappi;
    // End of variables declaration//GEN-END:variables
}
